import Head from "next/head";
import { BsFillMoonStarsFill, BsTelegram } from "react-icons/bs";
import { AiFillLinkedin, AiFillMail, AiFillInstagram } from "react-icons/ai";
import Image from "next/image";
import simeon from "../public/simeon.jpg";
import design from "../public/design.png";
import code from "../public/code.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/hyster.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Simeon Dimov Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">monicho</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-300 to-teal-500 bg-cyan-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Simeon Dimov
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Web developer and UX/UI designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              I am a second year ICT & Media Design student at Fontys, I am
              working on web products from A to B, from the design and research,
              to the programming and testing.
            </p>
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://www.linkedin.com/in/simeon-dimov-bb429016b/">
              <AiFillLinkedin />
            </a>
            <a href="mailto: simeondimow@gmail.com">
              <AiFillMail />
            </a>
            <a href="https://t.me/monichobg">
              <BsTelegram />{" "}
            </a>
            <a href="https://www.instagram.com/simeonshots/">
              <AiFillInstagram />{" "}
            </a>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white mx-auto">
              Services I offer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              I have been working on various university and industry projects
              during the time of my studies. I can do{" "}
              <span className="text-teal-500">ICT research, UX/UI design </span>
              and develop{" "}
              <span className="text-teal-500">web applications </span> with
              <span className="text-teal-500"> React/Native </span>
              and
              <span className="text-teal-500"> Tailwind CSS. </span>
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center  shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                className="mx-auto"
                src={design}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful designs
              </h3>
              <p className="py-2">
                I am creating both consumer and industrial grade designs
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">XD</p>
              <p className="text-gray-800 py-1">Sketch/Invision</p>
            </div>

            <div className="text-center  shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image className="mx-auto" src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Development/Web{" "}
              </h3>
              <p className="py-2">
                I have experience with React, AWS, C++(Arduino/ESP32), Google
                Cloud, InfluxDB and Firebase
              </p>
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">XD</p>
              <p className="text-gray-800 py-1">Sketch/Invision</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio - Highlights</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              I have been working on various university and industry projects
              during the time of my studies. I can do{" "}
              <span className="text-teal-500">ICT research, UX/UI design </span>
              and develop{" "}
              <span className="text-teal-500">web applications </span> with
              <span className="text-teal-500"> React/Native and Tailwind </span>
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="text-center  shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1 basis-1/3 ">
              <h4 className="text-3xl py-1">Utimaco website redesign</h4>
              <p className="text-md py-5 leading-8 text-gray-800">
                This was my first group university/industry project. We had the
                the task to redesign Utimaco's website with a "marketing
                approach" The Lo-Fi sketching was done in XD and Hi-Fi
                prototypes were done in Sketch and Invision. The website was
                programmed with Bootstrap, Vanilla JS, CSS and HTML.You can
                check the website{" "}
                <a className="text-teal-600" href="https://utimaco.github.io/">
                  {" "}
                  here.
                </a>
              </p>
              <Image className="rounded-lg" src={web1} />
            </div>

            <div className="text-center  shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1 basis-1/3">
              <h4 className="text-3xl py-1">Facimate App</h4>
              <p className="text-md py-5 leading-8 text-gray-800">
                This is my second university group project. The app allows you
                to find people for professional causes or you can match them by
                hobbies. I call it a LinkedIn and Tinder hybrid. The prototypes
                were done in Figma and the research for our concept app was
                conducted by me and my team following the ICT research methods.
                The actual PoF is based on React and Firebase and few animation
                and design libraries. You can check the whole project{" "}
                <a
                  className="text-teal-600"
                  href="https://sites.google.com/view/dynamercs-blog/home"
                >
                  {" "}
                  here.
                </a>
              </p>
              <Image className="rounded-lg" src={web2} />
            </div>

            <div className="text-center  shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1 basis-1/3 ">
              <h4 className="text-3xl py-1">
                Hyster-Yale Group tyre monitoring cross-platform app{" "}
              </h4>
              <p className="text-md py-5 leading-8 text-gray-800">
                This is the biggest project for me, it took me almost a year to
                develop it and it is still being developed by ICT interns from
                Fontys. I created the project from the beginning and conducted
                the whole research - technical, usability and design. It was
                designed in Adobe XD from scratch and it had more than 5
                revisions by me. Each component in the design is custom and
                built by me since the company is strict about licensing. I was
                responsible for the further development of the app with React
                Native, InfluxDB hosted on AWS and I used Victory Native
                visualization library. The app serves for optimizing the pumping
                process and monitoring of the port of Malta. It aims to improve
                the efficiency and sustainability of port operations. Tyres
                there are used on a huge scale, so an improvement of 5-10% per
                year in efficiency means a lot of resources, as well as less
                environmental impact.
              </p>
              <Image className="rounded-lg" src={web3} />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
